namespace BrewView.GraphQL
{
    public class Queries
    {
        public const string Brew = @"query Brew($productId : String){
  brew(productId: $productId){
    basic{
      ageLimit
      productShortName
      productStatusSaleName
      productId
      alcoholContent
      corkType
      volume
      introductionDate
      productId
      productLongName
      vintage
      volumType
    }
    classification{
      productTypeName
      mainProductTypeId
      mainProductTypeName
      productGroupId
      productGroupName
      productTypeId
      subProductTypeId
      subProductTypeName
    }
    description{
      characteristics{
        colour
        odour
        taste
      }
      bitterness
      freshness
      fullness
      recommendedFood{
        foodDesc
        foodId
      }
      sweetness
      tannins
    }
    ingredients{
      acid
      grapes{
        grapeDesc
        grapeId
        grapePct
      }
      sugar
    }
    lastChanged{
      date
    }
    logistics{
      manufacturerId
      manufacturerName
      vendorId
      vendorName
      wholesalerId
      wholesalerName
    }
    origins{
      origin{
        country
        countryId
        region
        regionId
        subRegion
        subRegionId
      }
      production{
        country
        countryId
        region
        regionId
      }
    }
    prices{
      salesPrice
      salesPricePrLiter
    }
    properties{
     sweetWine
     locallyProduced
     productionMethodStorage
     storagePotential
     vintageControlled 
    }
  }
}";

        public const string BrewByGtin = @"query GetBrewByCode($gtin: String){
  brewWithCode(gtin : $gtin){
    basic{
      productId
      productLongName
      alcoholContent
      volume
    }
    description{
      characteristics{
        colour
        odour
        taste
      }
      sweetness
      fullness
    }
  }
}";

        public const string Brews = @"query{
  brews{
    basic{
      productId
      productShortName
      alcoholContent
    }
    description{
      characteristics{
        colour
        odour
        taste
      }
    }
  }
}";
    }
}